services:
    notification:
        class: IrishDan\NotificationBundle\NotificationManager
        arguments: [ '@notification.channel_manager' ]
        calls:
            # - [setDatabaseNotificationManager, ['@notification.database_notification_manager']]

    notification.channel_manager:
        class: IrishDan\NotificationBundle\ChannelManager
        arguments: [ '@event_dispatcher', '%notification.available_channels%' ]
        calls: # These should be built automatically
            - [setChannel, ['database', '@notification.channel.database']]
            - [setChannel, ['mail', '@notification.channel.mail']]
            - [setChannel, ['pusher', '@notification.channel.pusher']]
            - [setChannel, ['nexmo', '@notification.channel.nexmo']]
            - [setChannel, ['slack','@notification.channel.slack']]

    notification.database_notification_manager:
        class: IrishDan\NotificationBundle\DatabaseNotificationManager
        arguments: [ '@doctrine.orm.entity_manager', '%notification.database_channel.configuration%' ]

    notification.pusher_manager:
        class: IrishDan\NotificationBundle\PusherManager
        arguments: [ '%notification.pusher_channel.configuration%' ]

    # Channels
    notification.channel.database:
        class: IrishDan\NotificationBundle\Channel\DefaultChannel
        arguments: [ '%notification.database_channel.enabled%' ]
        calls:
            - [ setDataFormatter, [ '@notification.database_data_formatter']]
            - [ setDispatcher, [ '@notification.database_message_dispatcher']]

    notification.channel.mail:
        class: IrishDan\NotificationBundle\Channel\DefaultChannel
        arguments: [ '%notification.mail_channel.enabled%' ]
        calls:
            - [ setDataFormatter, [ '@notification.mail_data_formatter']]
            - [ setDispatcher, [ '@notification.mail_message_dispatcher']]

    notification.channel.pusher:
        class: IrishDan\NotificationBundle\Channel\DefaultChannel
        arguments: [ '%notification.pusher_channel.enabled%' ]
        calls:
            - [ setDataFormatter, [ '@notification.pusher_data_formatter']]
            - [ setDispatcher, [ '@notification.pusher_message_dispatcher']]

    notification.channel.nexmo:
        class: IrishDan\NotificationBundle\Channel\DefaultChannel
        arguments: [ '%notification.nexmo_channel.enabled%' ]
        calls:
            - [ setDataFormatter, [ '@notification.nexmo_data_formatter']]
            - [ setDispatcher, [ '@notification.nexmo_message_dispatcher']]

    notification.channel.slack:
        class: IrishDan\NotificationBundle\Channel\DefaultChannel
        calls:
            - [ setDataFormatter, [ '@notification.slack_data_formatter']]
            - [ setDispatcher, [ '@notification.slack_message_dispatcher']]

    # Formatters
    notification.database_data_formatter:
        class: IrishDan\NotificationBundle\Formatter\DatabaseDataFormatter
        calls:
            - [setTemplating, ['@twig']]

    notification.mail_data_formatter:
        class: IrishDan\NotificationBundle\Formatter\MailDataFormatter
        arguments: [ '%notification.mail_channel.configuration%' ]
        # calls:
        #    - [setTemplating, ['@twig']]

    notification.pusher_data_formatter:
        class: IrishDan\NotificationBundle\Formatter\PusherDataFormatter
        # calls:
        #     - [setTemplating, ['@twig']]

    notification.nexmo_data_formatter:
        class: IrishDan\NotificationBundle\Formatter\NexmoDataFormatter
        arguments: ['%notification.nexmo_channel.configuration%']
        calls:
            - [setTemplating, ['@twig']]

    notification.slack_data_formatter:
        class: IrishDan\NotificationBundle\Formatter\SlackWebhookFormatter

    # Dispatchers
    notification.database_message_dispatcher:
        class: IrishDan\NotificationBundle\Dispatcher\DatabaseMessageDispatcher
        arguments: [ '@doctrine.orm.entity_manager', '%notification.database_channel.configuration%' ]

    notification.mail_message_dispatcher:
        class: IrishDan\NotificationBundle\Dispatcher\MailMessageDispatcher
        arguments: [ '@mailer' ]

    notification.pusher_message_dispatcher:
        class: IrishDan\NotificationBundle\Dispatcher\PusherMessageDispatcher
        arguments: [ '@notification.pusher_manager' ]

    notification.nexmo_message_dispatcher:
        class: IrishDan\NotificationBundle\Dispatcher\NexmoMessageDispatcher
        arguments: [ '%notification.nexmo_channel.configuration%' ]

    notification.slack_message_dispatcher:
        class: IrishDan\NotificationBundle\Dispatcher\SlackWebhookMessageDispatcher

    # Voters
    notification.pusher_channel_voter:
        class: IrishDan\NotificationBundle\Security\PusherChannelVoter
        arguments: [ '%notification.pusher_channel.enabled%', '%notification.pusher_channel.configuration%' ]
        tags:
            - { name: security.voter }
        public: false

    # Twig extensions
    notification.twig_extension:
        class: IrishDan\NotificationBundle\Twig\NotificationExtension
        public: false
        arguments: [ '@notification.pusher_manager', '@router', '@notification.database_notification_manager', '%notification.available_channels%']
        tags:
          - { name: twig.extension }

    # Commands
    notification.generation_command:
        class: IrishDan\NotificationBundle\Command\CreateNotificationCommand
        calls:
            - [setEnabledChannels, ['%notification.available_channels%']]
        tags:
            - { name: console.command }

    notification.command.generate_database_notification:
        class: IrishDan\NotificationBundle\Command\CreateDatabaseNotificationCommand
        calls:
            - [setEntityName, ['%notification.database_channel.configuration%']]
        tags:
            - { name: console.command }

# Create automatically
# broadcasting
    notification.broadcast.notifiable:
        class: IrishDan\NotificationBundle\Broadcast\Broadcast

    notification.broadcast.the_three_amigos:
        class: IrishDan\NotificationBundle\Broadcast\Broadcaster
        arguments: [ '@notification.broadcast.notifiable', '@notification.channel.slack', '%notification.broadcast.config.the_three_amigos%' ]

parameters:
    notification.broadcast.config.the_three_amigos:
        webhook: 'https://hooks.slack.com/services/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'
        token: 'A token'
        channel_type: default