services:
    notification.database_notification_manager:
        class: IrishDan\NotificationBundle\DatabaseNotificationManager
        arguments: [ '@doctrine', '%notification.channel.database.configuration%' ]

    notification.pusher_manager:
        class: IrishDan\NotificationBundle\PusherManager
        shared: false

    # Message adapters
    notification.adapter.database:
        class: IrishDan\NotificationBundle\Adapter\DatabaseMessageAdapter
        arguments: [ '@notification.database_notification_manager']
        public: false
        calls:
            - [setTemplating, ['@twig']] # @TODO: This needs defined only if configured
        tags:
            - { name: notification.adapter }

    notification.adapter.mail:
        class: IrishDan\NotificationBundle\Adapter\MailMessageAdapter
        arguments: ['@mailer' , '%notification.channel.mail.configuration%']
        public: false
        calls:
            - [setTemplating, ['@twig']]
        tags:
            - { name: notification.adapter }

    notification.adapter.pusher:
        class: IrishDan\NotificationBundle\Adapter\PusherMessageAdapter
        arguments: [ '@notification.pusher_manager']
        public: false
        calls:
            - [setTemplating, ['@twig']]
        tags:
            - { name: notification.adapter }

    notification.adapter.nexmo:
        class: IrishDan\NotificationBundle\Adapter\NexmoMessageAdapter
        arguments: [ '%notification.channel.nexmo.configuration%']
        public: false
        calls:
            - [setTemplating, ['@twig']]
        tags:
            - { name: notification.adapter }

    notification.adapter.slack:
        class: IrishDan\NotificationBundle\Adapter\SlackWebhookMessageAdapter
        public: false
        calls:
            - [setTemplating, ['@twig']]
        tags:
            - { name: notification.adapter }

    notification.adapter.logger:
        class: IrishDan\NotificationBundle\Adapter\LoggerMessageAdapter
        arguments: [ '@logger' ]
        public: false
        tags:
            - { name: notification.adapter }

    # Voters
    notification.pusher_channel_voter:
        class: IrishDan\NotificationBundle\Security\PusherChannelVoter
        arguments: [ '%notification.channel.pusher.enabled%', '%notification.channel.pusher.configuration%' ]
        tags:
            - { name: security.voter }
        public: false

    # Twig extensions
    notification.twig_extension:
        class: IrishDan\NotificationBundle\Twig\NotificationExtension
        public: false
        arguments: [ '@notification.pusher_manager', '@router', '@notification.database_notification_manager', '%notification.available_channels%']
        tags:
          - { name: twig.extension }

    # Commands
    # notification.command.generate_notification:
    #     class: IrishDan\NotificationBundle\Command\CreateNotificationCommand
    #     calls:
    #         - [setEnabledChannels, ['%notification.available_channels%']]
    #     tags:
    #         - { name: console.command }

    # notification.command.generate_database_notification:
    #     class: IrishDan\NotificationBundle\Command\CreateDatabaseNotificationCommand
    #     calls:
    #         - [setEntityName, ['%notification.channel.database.configuration%']]
    #     tags:
    #         - { name: console.command }

    # Event subscribers
    # notification.channel_subscriber:
    #     class: IrishDan\NotificationBundle\EventListener\MessageCRUDSubscriber
    #     arguments: [ '@notification.channel.event_channel', '@logger']
    #     tags:
    #         - { name: kernel.event_subscriber }

    # Broadcasting
    notification.broadcast.notifiable:
        public: false
        class: IrishDan\NotificationBundle\Broadcast\Broadcast

    # Maker commands
    notification.notification_maker:
        public: true
        class: IrishDan\NotificationBundle\Maker\NotificationMaker
        tags:
            - { name: maker.command }

    notification.database_notification_maker:
        public: true
        class: IrishDan\NotificationBundle\Maker\DatabaseNotificationMaker
        tags:
            - { name: maker.command }

    # vendor bundle: should not be using autowiring etc...
    IrishDan\NotificationBundle\Repository\NotificationRepository:
        autowire: true
        tags: ['doctrine.repository_service']

    # Aliases
    IrishDan\NotificationBundle\NotificationManager: '@notification.manager'