services:
    notification:
        class: IrishDan\NotificationBundle\NotificationManager
        arguments: [ '@notification.channel_manager' ]
        calls:
            # - [setDatabaseNotificationManager, ['@notification.database_notification_manager']]

    # notification.channel_manager:
    #     class: IrishDan\NotificationBundle\ChannelManager
    #     arguments: [ '@event_dispatcher', '%notification.available_channels%' ]
    #     calls:
    #         - [setChannel, ['database', '@notification.channel.database']]
    #         - [setChannel, ['mail', '@notification.channel.mail']]
    #         - [setChannel, ['pusher', '@notification.channel.pusher']]
    #         - [setChannel, ['nexmo', '@notification.channel.nexmo']]
    #         - [setChannel, ['slack','@notification.channel.slack']]

    notification.database_notification_manager:
        class: IrishDan\NotificationBundle\DatabaseNotificationManager
        arguments: [ '@doctrine', '%notification.channel.database.configuration%' ]

    notification.pusher_manager:
        class: IrishDan\NotificationBundle\PusherManager
        arguments: [ '%notification.channel.pusher.configuration%']

    # Channels
    # notification.channel.database:
    #     class: IrishDan\NotificationBundle\Channel\DefaultChannel
    #     arguments: [ '%notification.channel.database.enabled%', '%notification.channel.database.configuration%']
    #     calls:
    #         - [ setDataFormatter, [ '@notification.database_data_formatter']]
    #         - [ setDispatcher, [ '@notification.database_message_dispatcher']]

    # notification.channel.mail:
    #     class: IrishDan\NotificationBundle\Channel\DefaultChannel
    #     arguments: [ '%notification.channel.mail.enabled%', '%notification.channel.mail.configuration%' ]
    #     calls:
    #         - [ setDataFormatter, [ '@notification.mail_data_formatter']]
    #         - [ setDispatcher, [ '@notification.mail_message_dispatcher']]

    # notification.channel.pusher:
    #     class: IrishDan\NotificationBundle\Channel\DefaultChannel
    #     arguments: [ '%notification.channel.pusher.enabled%', '%notification.channel.pusher.configuration%' ]
    #     calls:
    #         - [ setDataFormatter, [ '@notification.pusher_data_formatter']]
    #         - [ setDispatcher, [ '@notification.pusher_message_dispatcher']]

    # notification.channel.nexmo:
    #     class: IrishDan\NotificationBundle\Channel\DefaultChannel
    #     arguments: [ '%notification.channel.nexmo.enabled%', '%notification.channel.nexmo.configuration%' ]
    #     calls:
    #         - [ setDataFormatter, [ '@notification.nexmo_data_formatter']]
    #         - [ setDispatcher, [ '@notification.nexmo_message_dispatcher']]

    # notification.channel.slack:
    #     class: IrishDan\NotificationBundle\Channel\DefaultChannel
    #     arguments: [ '%notification.channel.slack.enabled%', '%notification.channel.slack.configuration%' ]
    #     calls:
    #         - [ setDataFormatter, [ '@notification.slack_data_formatter']]
    #         - [ setDispatcher, [ '@notification.slack_message_dispatcher']]

    # Formatters
    notification.database_data_formatter:
        class: IrishDan\NotificationBundle\Formatter\DatabaseDataFormatter
        calls:
            - [setTemplating, ['@twig']]

    notification.mail_data_formatter:
        class: IrishDan\NotificationBundle\Formatter\MailDataFormatter
        arguments: [ '%notification.channel.mail.configuration%' ]
        calls:
           - [setTemplating, ['@twig']]

    notification.pusher_data_formatter:
        class: IrishDan\NotificationBundle\Formatter\PusherDataFormatter
        arguments: [ '@notification.pusher_manager']
        calls:
            - [setTemplating, ['@twig']]

    notification.nexmo_data_formatter:
        class: IrishDan\NotificationBundle\Formatter\NexmoDataFormatter
        arguments: ['%notification.channel.nexmo.configuration%']
        calls:
            - [setTemplating, ['@twig']]

    notification.slack_data_formatter:
        class: IrishDan\NotificationBundle\Formatter\SlackWebhookFormatter

    # Dispatchers
    notification.database_message_dispatcher:
        class: IrishDan\NotificationBundle\Dispatcher\DatabaseMessageDispatcher
        arguments: [ '@notification.database_notification_manager' ]

    notification.mail_message_dispatcher:
        class: IrishDan\NotificationBundle\Dispatcher\MailMessageDispatcher
        arguments: [ '@mailer' ]

    notification.pusher_message_dispatcher:
        class: IrishDan\NotificationBundle\Dispatcher\PusherMessageDispatcher
        arguments: [ '@notification.pusher_manager' ]

    notification.nexmo_message_dispatcher:
        class: IrishDan\NotificationBundle\Dispatcher\NexmoMessageDispatcher
        arguments: [ '%notification.channel.nexmo.configuration%' ]

    notification.slack_message_dispatcher:
        class: IrishDan\NotificationBundle\Dispatcher\SlackWebhookMessageDispatcher

    # Voters
    notification.pusher_channel_voter:
        class: IrishDan\NotificationBundle\Security\PusherChannelVoter
        arguments: [ '%notification.channel.pusher.enabled%', '%notification.channel.pusher.configuration%' ]
        tags:
            - { name: security.voter }
        public: false

    # Twig extensions
    notification.twig_extension:
        class: IrishDan\NotificationBundle\Twig\NotificationExtension
        public: false
        arguments: [ '@notification.pusher_manager', '@router', '@notification.database_notification_manager', '%notification.available_channels%']
        tags:
          - { name: twig.extension }

    # Commands
    notification.generation_command:
        class: IrishDan\NotificationBundle\Command\CreateNotificationCommand
        calls:
            - [setEnabledChannels, ['%notification.available_channels%']]
        tags:
            - { name: console.command }

    notification.command.generate_database_notification:
        class: IrishDan\NotificationBundle\Command\CreateDatabaseNotificationCommand
        calls:
            - [setEntityName, ['%notification.channel.database.configuration%']]
        tags:
            - { name: console.command }

    # Event channel
    notification.channel.event_channel:
        class: IrishDan\NotificationBundle\Channel\EventChannel
        arguments: [ '@event_dispatcher']
        calls:
            - [ setDispatchers, [ 'mail', '@notification.mail_message_dispatcher']]

    # Event subscribers
    notification.message_crud_subscriber:
        class: IrishDan\NotificationBundle\EventListener\MessageCRUDSubscriber
        arguments: [ '@notification.channel.event_channel', '@logger']
        tags:
            - { name: kernel.event_subscriber }

# Create automatically
# broadcasting
    notification.broadcast.notifiable:
        class: IrishDan\NotificationBundle\Broadcast\Broadcast

    notification.broadcast.the_three_amigos:
        class: IrishDan\NotificationBundle\Broadcast\Broadcaster
        arguments: [ '@notification.broadcast.notifiable', '@notification.channel.slack', '%notification.broadcast.config.the_three_amigos%' ]