services:
    notification.manager:
        class: IrishDan\NotificationBundle\NotificationManager
        arguments: [ '@notification.channel_manager', '@notification.database_notification_manager' ]
        public: true

    notification.database_notification_manager:
        class: IrishDan\NotificationBundle\DatabaseNotificationManager
        arguments: [ '@doctrine', '%notification.channel.database.configuration%' ]

    notification.pusher_manager:
        class: IrishDan\NotificationBundle\PusherManager
        arguments: [ '%notification.channel.pusher.configuration%']

    # Message adapters
    notification.adapter.database:
        class: IrishDan\NotificationBundle\Adapter\DatabaseMessageAdapter
        arguments: [ '@notification.database_notification_manager']
        calls:
            - [setTemplating, ['@twig']]

    notification.adapter.mail:
        class: IrishDan\NotificationBundle\Adapter\MailMessageAdapter
        arguments: ['@mailer' , '%notification.channel.mail.configuration%']
        calls:
            - [setTemplating, ['@twig']]

    notification.adapter.pusher:
        class: IrishDan\NotificationBundle\Adapter\PusherMessageAdapter
        arguments: [ '@notification.pusher_manager']
        calls:
            - [setTemplating, ['@twig']]

    notification.adapter.nexmo:
        class: IrishDan\NotificationBundle\Adapter\NexmoMessageAdapter
        arguments: [ '%notification.channel.nexmo.configuration%']
        calls:
            - [setTemplating, ['@twig']]

    notification.adapter.slack:
        class: IrishDan\NotificationBundle\Adapter\SlackWebhookMessageAdapter
        calls:
            - [setTemplating, ['@twig']]

    # Voters
    notification.pusher_channel_voter:
        class: IrishDan\NotificationBundle\Security\PusherChannelVoter
        arguments: [ '%notification.channel.pusher.enabled%', '%notification.channel.pusher.configuration%' ]
        tags:
            - { name: security.voter }
        public: false

    # Twig extensions
    notification.twig_extension:
        class: IrishDan\NotificationBundle\Twig\NotificationExtension
        public: false
        arguments: [ '@notification.pusher_manager', '@router', '@notification.database_notification_manager', '%notification.available_channels%']
        tags:
          - { name: twig.extension }

    # Commands
    notification.generation_command:
        class: IrishDan\NotificationBundle\Command\CreateNotificationCommand
        calls:
            - [setEnabledChannels, ['%notification.available_channels%']]
        tags:
            - { name: console.command }

    notification.command.generate_database_notification:
        class: IrishDan\NotificationBundle\Command\CreateDatabaseNotificationCommand
        calls:
            - [setEntityName, ['%notification.channel.database.configuration%']]
        tags:
            - { name: console.command }

    # Event channel
    notification.channel.event_channel:
        class: IrishDan\NotificationBundle\Channel\EventChannel
        arguments: [ '@event_dispatcher']
        calls:
            - [ setAdapters, [ 'database', '@notification.adapter.database']]
            - [ setAdapters, [ 'mail', '@notification.adapter.mail']]
            - [ setAdapters, [ 'nexmo', '@notification.adapter.nexmo']]
            - [ setAdapters, [ 'slack', '@notification.adapter.slack']]
            - [ setAdapters, [ 'pusher', '@notification.adapter.pusher']]

    # Event subscribers
    notification.message_crud_subscriber:
        class: IrishDan\NotificationBundle\EventListener\MessageCRUDSubscriber
        arguments: [ '@notification.channel.event_channel', '@logger']
        tags:
            - { name: kernel.event_subscriber }

    # broadcasting
    notification.broadcast.notifiable:
        class: IrishDan\NotificationBundle\Broadcast\Broadcast