services:
    notification:
        class: NotificationBundle\NotificationManager
        arguments: [ '@notification.channel_manager' ]
        calls:
            - [setDatabaseNotificationManager, ['@notification.database_notification_manager']]

    notification.channel_manager:
        class: NotificationBundle\ChannelManager
        arguments: [ '@event_dispatcher', '%notification.available_channels%' ]
        calls:
            - [setChannel, ['database', '@notification.database_channel']]
            - [setChannel, ['mail', '@notification.mail_channel']]
            - [setChannel, ['pusher', '@notification.pusher_channel']]

    notification.database_notification_manager:
        class: NotificationBundle\DatabaseNotificationManager
        arguments: [ '@doctrine.orm.entity_manager', '%notification.database_channel.configuration%' ]

    notification.pusher_manager:
        class: NotificationBundle\PusherManager
        arguments: [ '%notification.pusher_channel.configuration%' ]

    # Channels
    notification.database_channel:
        class: NotificationBundle\Channel\DefaultChannel
        arguments: [ '%notification.database_channel.enabled%' ]
        calls:
            - [ setDataFormatter, [ '@notification.database_data_formatter']]
            - [ setDispatcher, [ '@notification.database_message_dispatcher']]

    notification.mail_channel:
        class: NotificationBundle\Channel\DefaultChannel
        arguments: [ '%notification.mail_channel.enabled%' ]
        calls:
            - [ setDataFormatter, [ '@notification.mail_data_formatter']]
            - [ setDispatcher, [ '@notification.mail_message_dispatcher']]

    notification.pusher_channel:
        class: NotificationBundle\Channel\DefaultChannel
        arguments: [ '%notification.pusher_channel.enabled%' ]
        calls:
            - [ setDataFormatter, [ '@notification.pusher_data_formatter']]
            - [ setDispatcher, [ '@notification.pusher_message_dispatcher']]

    # Formatters
    notification.database_data_formatter:
        class: NotificationBundle\Formatter\DatabaseDataFormatter
        calls:
            - [setTemplating, ['@twig']]

    notification.mail_data_formatter:
        class: NotificationBundle\Formatter\MailDataFormatter
        arguments: [ '%notification.mail_channel.configuration%' ]
        calls:
            - [setTemplating, ['@twig']]

    notification.pusher_data_formatter:
        class: NotificationBundle\Formatter\PusherDataFormatter
        calls:
            - [setTemplating, ['@twig']]

    # Dispatchers
    notification.database_message_dispatcher:
        class: NotificationBundle\Dispatcher\DatabaseMessageDispatcher
        arguments: [ '@doctrine.orm.entity_manager', '%notification.database_channel.configuration%' ]

    notification.mail_message_dispatcher:
        class: NotificationBundle\Dispatcher\MailMessageDispatcher
        arguments: [ '@mailer' ]

    notification.pusher_message_dispatcher:
        class: NotificationBundle\Dispatcher\PusherMessageDispatcher
        arguments: [ '@notification.pusher_manager' ]

    # Voters
    notification.pusher_channel_voter:
        class: NotificationBundle\Security\PusherChannelVoter
        arguments: [ '%notification.pusher_channel.enabled%', '%notification.pusher_channel.configuration%' ]
        tags:
            - { name: security.voter }
        public: false

    # Twig extensions
    notification.twig_extension:
        class: NotificationBundle\Twig\NotificationExtension
        public: false
        arguments: [ '@notification.pusher_manager', '@router', '@notification']
        tags:
          - { name: twig.extension }

    # Commands
    notification.generation_command:
        class: NotificationBundle\Command\CreateNotificationCommand
        calls:
            - [setEnabledChannels, ['%notification.available_channels%']]
        tags:
            - { name: console.command }

    notification.command.generate_database_notification:
        class: NotificationBundle\Command\CreateDatabaseNotificationCommand
        calls:
            - [setEntityName, ['%notification.database_channel.configuration%']]
        tags:
            - { name: console.command }
